FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY src src
COPY public public
COPY tsconfig.json tsconfig.json
COPY tsconfig.app.json tsconfig.app.json
COPY tsconfig.node.json tsconfig.node.json
COPY tailwind.config.js tailwind.config.js
COPY postcss.config.js postcss.config.js
COPY vite.config.ts vite.config.ts
COPY index.html index.html

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
