services:
  backend:
    build: ./backend
    ports:
      - "4000:4000"
    volumes:
      - "./backend/src:/app/src"
    env_file:
      - ./backend/.env
      - ./backend/db.env
    develop:
      watch:
        - action: sync+restart
          path: .
          target: backend/src
          ignore:
            - node_modules/
  db:
    image: postgres:16
    restart: always
    env_file:
      - ./backend/db.env
    ports:
      - 5435:5432
    volumes:
      - portfolio_db:/var/lib/postgresql/data
  
volumes:
  portfolio_db: