FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY src src
COPY tsconfig.json .

RUN npm run build

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/build ./build

RUN mkdir -p uploads

EXPOSE 3002

CMD ["node", "build/index.js"]