FROM node:lts-alpine

RUN mkdir /app
WORKDIR /app
FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY src src
COPY tsconfig.json .

RUN mkdir -p uploads

EXPOSE 3002

CMD ["npm", "run", "start"]